# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kern_gauss <- function(X_one, X_two, bandwidth) {
    .Call('_gKRLS_kern_gauss', PACKAGE = 'gKRLS', X_one, X_two, bandwidth)
}

#' Internal C++ function to calculate marginal effects
cpp_gkrls_me <- function(std_X_train, std_X_test, bandwidth, family, mahal, sd_y, tS, fe_mean, re_mean, all_mean, vcov_ridge, FE_matrix_test, W_Matrix, WX_test, WX_train, raw_X_test, std_mean, std_whiten, type_mfx, fd_matrix, std_fd_matrix) {
    .Call('_gKRLS_cpp_gkrls_me', PACKAGE = 'gKRLS', std_X_train, std_X_test, bandwidth, family, mahal, sd_y, tS, fe_mean, re_mean, all_mean, vcov_ridge, FE_matrix_test, W_Matrix, WX_test, WX_train, raw_X_test, std_mean, std_whiten, type_mfx, fd_matrix, std_fd_matrix)
}

#' Create the sketched kernel
#' @export
create_sketched_kernel <- function(X_test, X_train, tS, bandwidth) {
    .Call('_gKRLS_create_sketched_kernel', PACKAGE = 'gKRLS', X_test, X_train, tS, bandwidth)
}

