# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Evaluate the kernel distance between two vectors.
kern_gauss <- function(X_one, X_two, bandwidth) {
    .Call('_gKRLS_kern_gauss', PACKAGE = 'gKRLS', X_one, X_two, bandwidth)
}

#' Create the sketched kernel
#' @export
create_sketched_kernel <- function(X_test, X_train, tS, bandwidth) {
    .Call('_gKRLS_create_sketched_kernel', PACKAGE = 'gKRLS', X_test, X_train, tS, bandwidth)
}

